import { getChatGPTUser } from "../../chatgpt-auth";
import { getDb } from "../../../db";
import { auditLogs } from "../../../db/schema";
import { desc, eq } from "drizzle-orm";
import { getOrCreateProfile } from "../../../src/server/profile";

export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:"Não autenticado"},{status:401});try{const profile=await getOrCreateProfile(user);const query=getDb().select().from(auditLogs).orderBy(desc(auditLogs.createdAt)).limit(200);const rows=profile.role==="CONSULTA"?await query.where(eq(auditLogs.userId,user.userId)):await query;return Response.json({audits:rows.map(row=>({id:row.id,timestamp:row.createdAt,user:row.userName,operation:row.operation,module:row.module,result:row.result,status:row.status,fileName:row.fileName??undefined,processedCount:row.processedCount??undefined,okCount:row.okCount??undefined,divergentCount:row.divergentCount??undefined,missingCount:row.missingCount??undefined}))})}catch(error){return Response.json({error:error instanceof Error?error.message:"Falha ao consultar auditoria"},{status:500})}}

export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:"Não autenticado"},{status:401});try{const payload=await request.json() as Record<string,unknown>;await getDb().insert(auditLogs).values({id:String(payload.id??crypto.randomUUID()),userId:user.userId,userName:String(payload.user??user.displayName),operation:String(payload.operation??""),module:String(payload.module??""),result:String(payload.result??""),status:String(payload.status??"SUCESSO"),fileName:payload.fileName?String(payload.fileName):null,processedCount:Number(payload.processedCount)||null,okCount:Number(payload.okCount)||null,divergentCount:Number(payload.divergentCount)||null,missingCount:Number(payload.missingCount)||null,createdAt:String(payload.timestamp??new Date().toISOString())});return Response.json({ok:true},{status:201});}catch(error){return Response.json({error:error instanceof Error?error.message:"Falha ao registrar auditoria"},{status:500})}}
