"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Boxes, Bus, CalendarDays, Check, Download, FileSpreadsheet, HeartPulse, Search, Stethoscope, Trash2, Upload, UsersRound } from "lucide-react";
import type { ComparisonRow } from "../../../src/types";
import { readExcel, exportComparisonExcel } from "../../../src/services/excel";
import { processPayroll } from "../../../src/modules/payroll/processor";
import { comparePlan, parseReference, type ComparisonKind } from "../../../src/modules/comparisons/processor";
import { formatCpf } from "../../../src/utils/cpf";
import { formatMoney } from "../../../src/utils/money";
import { FileDropzone } from "../components/FileDropzone";
import { ConfirmationModal, EmptyState, MetricCard, ProcessingLog, StatusBadge } from "../components/Common";
import { useApp } from "../state/AppContext";

type Tab = "overview" | "health" | "dental" | "benefits" | "imports";
const tabs: { id: Tab; label: string }[] = [{ id:"overview",label:"Visão geral"},{id:"health",label:"Plano de Saúde"},{id:"dental",label:"Plano Odontológico"},{id:"benefits",label:"Benefícios"},{id:"imports",label:"Importações"}];

export function PayrollPage() {
  const app = useApp();
  const [tab, setTab] = useState<Tab>(app.activePayroll ? "overview" : "imports");
  const [removeOpen, setRemoveOpen] = useState(false);
  return <>
    <div className="page-heading compact"><div><h2>Dados da Folha</h2><p>Importe uma vez e reutilize a folha em todas as conferências.</p></div></div>
    {app.activePayroll && <div className="payroll-summary"><span className="document-icon">XLS</span><div><small>FOLHA ATIVA</small><strong>{app.activePayroll.fileName}</strong><em>{app.activePayroll.records.length} colaboradores reconhecidos</em></div><div><small>COMPETÊNCIA</small><strong>{app.activePayroll.competence}</strong></div><div><small>IMPORTADA EM</small><strong>{new Date(app.activePayroll.importedAt).toLocaleDateString("pt-BR")}</strong><em>{new Date(app.activePayroll.importedAt).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</em></div><div><small>USUÁRIO</small><strong>{app.activePayroll.importedBy}</strong></div><button className="button secondary" onClick={() => setTab("imports")}><Upload size={15}/> Trocar folha</button><button className="icon-danger" title="Remover folha ativa" onClick={() => setRemoveOpen(true)}><Trash2 size={17}/></button></div>}
    <div className="tabs">{tabs.map(item => <button className={tab === item.id ? "active" : ""} key={item.id} onClick={() => setTab(item.id)}>{item.label}</button>)}</div>
    {tab === "overview" && <PayrollOverview />}
    {tab === "imports" && <PayrollImport onDone={() => setTab("overview")} />}
    {tab === "health" && <PlanComparison kind="health" />}
    {tab === "dental" && <PlanComparison kind="dental" />}
    {tab === "benefits" && <Benefits />}
    <ConfirmationModal open={removeOpen} danger title="Remover a folha ativa?" description="A folha deixará de estar disponível e os comparativos atuais serão limpos. O arquivo original não será alterado." confirmLabel="Remover folha" onClose={() => setRemoveOpen(false)} onConfirm={() => { app.setActivePayroll(null); app.addAudit({ operation:"Removeu a folha ativa", module:"Folha", result:"Folha removida", status:"AVISO" }); app.toast("success","Folha ativa removida"); setTab("imports"); }} />
  </>;
}

function PayrollOverview() {
  const { activePayroll, health, dental } = useApp();
  if (!activePayroll) return <EmptyState icon={<FileSpreadsheet/>} title="Importe a Folha de Pagamento" description="A folha ativa será usada pelos comparativos de saúde, odontológico e benefícios." />;
  const healthColumns = Math.max(0, ...activePayroll.records.map(record => record.healthColumns));
  const dentalColumns = Math.max(0, ...activePayroll.records.map(record => record.dentalColumns));
  return <div className="stack-gap"><div className="metrics-grid"><MetricCard label="COLABORADORES" value={activePayroll.records.length} detail="CPFs únicos"/><MetricCard label="COLUNAS PLANO SAÚDE" value={healthColumns} detail="somadas por CPF" tone={healthColumns ? "success":"warning"}/><MetricCard label="COLUNAS PLANO ODONTO" value={dentalColumns} detail="somadas por CPF" tone={dentalColumns ? "success":"warning"}/><MetricCard label="CONFERÊNCIAS" value={[health,dental].filter(Boolean).length} detail="de 2 concluídas"/></div><section className="surface"><div className="section-header"><div><h3>Diagnóstico da importação</h3><p>Detecção automática de estrutura e colunas.</p></div><StatusBadge status="PROCESSAMENTO CONCLUÍDO"/></div><div className="diagnostic-list">{activePayroll.logs.map((log,index)=><div key={index}><Check size={14}/><span>{log}</span></div>)}</div></section></div>;
}

function PayrollImport({ onDone }: { onDone: () => void }) {
  const { user, setActivePayroll, addAudit, toast } = useApp();
  const [files,setFiles]=useState<File[]>([]); const [competence,setCompetence]=useState(new Date().toLocaleDateString("pt-BR",{month:"2-digit",year:"numeric"})); const [logs,setLogs]=useState<string[]>([]); const [progress,setProgress]=useState(0); const [busy,setBusy]=useState(false);
  const run=async()=>{ if(!files[0]){toast("warning","Selecione a Folha de Pagamento","Envie um arquivo XLS ou XLSX antes de continuar.");return;} setBusy(true);setLogs(["Lendo arquivo..."]);setProgress(15);try{const workbook=await readExcel(files[0]);setLogs(current=>[...current,"Procurando cabeçalhos nas abas...",...workbook.warnings]);setProgress(48);await new Promise(resolve=>setTimeout(resolve,80));const payroll=processPayroll(workbook,competence,user.name);setLogs(payroll.logs);setProgress(100);setActivePayroll(payroll);addAudit({operation:"Importou Folha de Pagamento",module:"Folha",result:`${payroll.records.length} colaboradores encontrados`,status:"SUCESSO",fileName:payroll.fileName,processedCount:payroll.records.length});toast("success","Folha importada com sucesso",`${payroll.records.length} colaboradores foram reconhecidos.`);onDone();}catch(error){const message=error instanceof Error?error.message:"Falha inesperada ao ler o arquivo.";setLogs(current=>[...current,message]);toast("error","Não foi possível importar a folha",message);}finally{setBusy(false);}};
  return <section className="surface import-surface"><div className="section-header"><div><h3>Importar Folha de Pagamento</h3><p>O sistema procura o cabeçalho, mesmo quando ele não está na primeira linha.</p></div></div><div className="import-form"><label className="field"><span>Competência</span><div className="input-with-icon"><CalendarDays size={16}/><input value={competence} onChange={event=>setCompetence(event.target.value)} placeholder="07/2026"/></div></label><FileDropzone accept=".xls,.xlsx" files={files} onFiles={setFiles} label="Arraste a Folha de Pagamento" hint="ou clique para selecionar um arquivo XLS/XLSX"/><ProcessingLog logs={logs} progress={progress}/><div className="form-actions"><button className="button primary" disabled={busy||!files.length} onClick={run}><Upload size={16}/>{busy?"Processando...":"Importar e tornar ativa"}</button></div></div></section>;
}

function PlanComparison({ kind }: { kind: ComparisonKind }) {
  const app=useApp(); const state=kind==="health"?app.health:app.dental; const setState=kind==="health"?app.setHealth:app.setDental; const label=kind==="health"?"Plano de Saúde":"Plano Odontológico";
  const [files,setFiles]=useState<File[]>([]);const[tolerance,setTolerance]=useState(app.settings.financialTolerance.toFixed(2).replace(".",","));const[busy,setBusy]=useState(false);const[logs,setLogs]=useState<string[]>([]);const[progress,setProgress]=useState(0);const[query,setQuery]=useState("");const[filter,setFilter]=useState("TODOS");const[page,setPage]=useState(1);
  useEffect(()=>{setTolerance(app.settings.financialTolerance.toFixed(2).replace(".",","))},[app.settings.financialTolerance]);
  const filtered=useMemo(()=>{const normalized=query.replace(/\D/g,"").toLowerCase();return(state?.rows??[]).filter(row=>(!query||row.name.toLowerCase().includes(query.toLowerCase())||row.cpf.includes(normalized))&&(filter==="TODOS"||(filter==="OK"&&row.status==="OK")||(filter==="DIVERGENTES"&&row.status==="DIVERGENTE")||(filter==="AUSENTES"&&row.status.includes("NÃO LOCALIZADO"))));},[state,query,filter]); const perPage=20;const totalPages=Math.max(1,Math.ceil(filtered.length/perPage));const visible=filtered.slice((page-1)*perPage,page*perPage);
  const run=async()=>{if(!app.activePayroll){app.toast("warning","Nenhuma folha ativa",`Importe a Folha de Pagamento antes de conferir ${label}.`);return;}if(!files[0]){app.toast("warning","Selecione o arquivo de referência");return;}setBusy(true);setLogs(["Lendo arquivo de referência...","Procurando cabeçalho e coluna CPF..."]);setProgress(22);try{const workbook=await readExcel(files[0]);setProgress(48);const reference=parseReference(workbook,kind);setLogs(current=>[...current,`${reference.length} CPFs encontrados na referência.`,`Comparando valores de ${label}...`]);const result=comparePlan(app.activePayroll,reference,kind,Number(tolerance.replace(",","."))||0.01);setProgress(100);setLogs(current=>[...current,`${result.summary.divergent} divergência(s) encontrada(s).`,`Processamento concluído.`]);setState({...result,processedAt:new Date().toISOString(),fileName:files[0].name});app.addAudit({operation:`Comparou ${label}`,module:label,result:`${result.summary.ok} OK, ${result.summary.divergent} divergentes, ${result.summary.missing} ausentes`,status:result.summary.divergent||result.summary.missing?"AVISO":"SUCESSO",fileName:files[0].name,processedCount:result.summary.total,okCount:result.summary.ok,divergentCount:result.summary.divergent,missingCount:result.summary.missing});app.toast("success","Comparativo concluído",`${result.summary.divergent} divergências e ${result.summary.missing} ausências encontradas.`);}catch(error){app.toast("error","Não foi possível iniciar o comparativo",error instanceof Error?error.message:"Verifique o arquivo informado.");}finally{setBusy(false);}};
  if(!app.activePayroll)return <EmptyState icon={kind==="health"?<HeartPulse/>:<Stethoscope/>} title="A Folha de Pagamento é obrigatória" description={`Importe a folha ativa antes de enviar o arquivo de referência do ${label}.`}/>;
  return <div className="stack-gap">{!state&&<section className="surface import-surface"><div className="section-header"><div><h3>Conferência · {label}</h3><p>A folha ativa será comparada ao arquivo de referência abaixo.</p></div><span className="status-badge neutral">Folha: {app.activePayroll.competence}</span></div><div className="import-form"><div className="two-fields"><div className="grow"><FileDropzone accept=".xls,.xlsx" files={files} onFiles={setFiles} label={`Arraste a referência de ${label}`} /></div><label className="field narrow"><span>Tolerância financeira</span><div className="money-input"><span>R$</span><input value={tolerance} onChange={event=>setTolerance(event.target.value)}/></div><small>Padrão: R$ {app.settings.financialTolerance.toFixed(2).replace(".",",")}</small></label></div><ProcessingLog logs={logs} progress={progress}/><div className="form-actions"><button className="button primary" disabled={busy||!files.length} onClick={run}>{busy?"Comparando...":"Iniciar comparativo"}</button></div></div></section>}
    {state&&<><div className="result-title"><div><span className="status-badge success">CONCLUÍDO</span><h3>Resultado · {label}</h3><p>Referência: {state.fileName} · {new Date(state.processedAt).toLocaleString("pt-BR")}</p></div><div><button className="button secondary" onClick={()=>setState(null)}>Novo comparativo</button><button className="button primary" onClick={()=>exportComparisonExcel(state.rows,`Comparativo_${kind}_${app.activePayroll?.competence.replace("/","-")}.xlsx`,label)}><Download size={16}/> Gerar Excel</button></div></div><div className="metrics-grid five"><MetricCard label="CPFS COMPARADOS" value={state.summary.total}/><MetricCard label="VALORES OK" value={state.summary.ok} tone="success"/><MetricCard label="DIVERGÊNCIAS" value={state.summary.divergent} tone="danger"/><MetricCard label="AUSENTES" value={state.summary.missing} tone="warning"/><MetricCard label="DIFERENÇA TOTAL" value={formatMoney(state.summary.differenceTotal)} tone={Math.abs(state.summary.differenceTotal)>.01?"danger":"success"}/></div><section className="surface table-surface"><div className="table-toolbar"><div className="search-box"><Search size={16}/><input placeholder="Pesquisar nome ou CPF" value={query} onChange={event=>{setQuery(event.target.value);setPage(1);}}/></div><div className="filter-pills">{["TODOS","OK","DIVERGENTES","AUSENTES"].map(item=><button className={filter===item?"active":""} key={item} onClick={()=>{setFilter(item);setPage(1);}}>{item}</button>)}</div><span>{filtered.length} resultado(s)</span></div><ComparisonTable rows={visible} valueLabel={kind==="health"?"Saúde Folha":"Odonto Folha"}/><div className="pagination"><span>Página {page} de {totalPages}</span><div><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>Anterior</button><button disabled={page===totalPages} onClick={()=>setPage(value=>value+1)}>Próxima</button></div></div></section></>}</div>;
}

function ComparisonTable({rows,valueLabel}:{rows:ComparisonRow[];valueLabel:string}){const{settings}=useApp();return <div className="table-scroll"><table className="data-table"><thead><tr><th>Nome</th><th>CPF</th><th className="right">{valueLabel}</th><th className="right">Referência</th><th className="right">Diferença</th><th className="right">Líquido</th><th className="center">Colunas</th><th>Status</th></tr></thead><tbody>{rows.map(row=><tr className={row.status==="DIVERGENTE"?"row-danger":row.status.includes("NÃO LOCALIZADO")?"row-warning":""} key={row.id}><td><strong>{row.name}</strong></td><td className="mono">{formatCpf(row.cpf,settings.maskCpf)}</td><td className="right">{formatMoney(row.payrollValue)}</td><td className="right">{formatMoney(row.referenceValue)}</td><td className={`right ${row.difference&&Math.abs(row.difference)>.01?"negative":"positive"}`}>{formatMoney(row.difference)}</td><td className="right">{formatMoney(row.liquid)}</td><td className="center">{row.columnCount}</td><td><StatusBadge status={row.status}/></td></tr>)}</tbody></table>{!rows.length&&<div className="table-empty">Nenhum registro corresponde aos filtros aplicados.</div>}</div>}

function Benefits(){
  const app=useApp();const[selected,setSelected]=useState<string|null>(null);const[files,setFiles]=useState<File[]>([]);const[analysis,setAnalysis]=useState<string[]>([]);const[busy,setBusy]=useState(false);
  const cards=[{id:"aggregation",label:"Agregamento",desc:"Importe e mapeie eventos agregados.",icon:<Boxes/>},{id:"transport",label:"Vale Transporte",desc:"Controle e confira descontos de transporte.",icon:<Bus/>},{id:"other",label:"Outros Benefícios",desc:"Processador genérico para novos benefícios.",icon:<UsersRound/>}];
  const analyze=async()=>{setBusy(true);try{const results:string[]=[];for(const file of files){const workbook=await readExcel(file);for(const sheet of workbook.sheets){const recognized=sheet.headers.filter(header=>["NOME","COLABORADOR","CPF","DATA","VALOR","TIPO","COMPETENCIA","STATUS"].some(alias=>header.toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").includes(alias)));results.push(`${file.name} · aba ${sheet.name}: ${sheet.rows.length} registros; campos ${recognized.join(", ")||"não mapeados"}.`);}}setAnalysis(results);app.addAudit({operation:"Analisou estrutura de benefício",module:"Benefícios",result:`${files.length} arquivo(s) analisado(s)`,status:results.some(item=>item.includes("não mapeados"))?"AVISO":"SUCESSO",processedCount:files.length});app.toast("success","Estrutura analisada","Confira os campos reconhecidos antes de definir as regras do benefício.");}catch(error){app.toast("error","Falha ao analisar benefício",error instanceof Error?error.message:undefined)}finally{setBusy(false)}};
  return <div className="stack-gap">{!selected?<div className="tool-card-grid benefit-grid">{cards.map(card=><button className="tool-card" key={card.id} onClick={()=>{setSelected(card.id);setFiles([]);setAnalysis([])}}><span>{card.icon}</span><strong>{card.label}</strong><p>{card.desc}</p><em>Abrir ferramenta →</em></button>)}</div>:<section className="surface import-surface"><div className="section-header"><div><button className="back-link" onClick={()=>setSelected(null)}>← Benefícios</button><h3>{cards.find(card=>card.id===selected)?.label}</h3><p>Processador modular com detecção de Nome, CPF, Data, Valor, Tipo, Competência e Status.</p></div></div><div className="import-form"><FileDropzone accept=".xls,.xlsx" multiple files={files} onFiles={setFiles}/><div className="inline-warning"><AlertTriangle/><span><strong>Mapeamento flexível</strong> As regras específicas deste benefício podem ser adicionadas sem alterar os comparativos existentes.</span></div>{analysis.length>0&&<ProcessingLog logs={analysis} progress={100}/>}<button className="button primary" disabled={!files.length||busy} onClick={analyze}>{busy?"Analisando...":"Analisar estrutura"}</button></div></section>}</div>
}
