"use client";

import { useCallback, useMemo, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowUp, Combine, Copy, Download, FileDiff, FileImage, FileInput, Files, FileStack, Image as ImageIcon, RotateCw, Scissors, Trash2, Upload, WandSparkles } from "lucide-react";
import { FileDropzone } from "../components/FileDropzone";
import { EmptyState, MetricCard, StatusBadge } from "../components/Common";
import { PdfCanvas, PdfPageCount } from "../components/PdfCanvas";
import { extractPdfText, imagesToPdf, mergePdfs, organizePdf, pdfToImages, splitPdf, type PageInstruction } from "../../../src/services/pdf";
import { useApp } from "../state/AppContext";
import { PdfEditor } from "./pdf/PdfEditor";
import { OvertimeTool } from "./pdf/OvertimeTool";

type Tool="home"|"editor"|"merge"|"split"|"organize"|"converter"|"overtime"|"compare";
const tools:{id:Tool;label:string;description:string;icon:typeof Files}[]=[{id:"editor",label:"Editor de PDF",description:"Adicione texto, apague áreas e desenhe elementos.",icon:WandSparkles},{id:"merge",label:"Juntar PDFs",description:"Ordene e mescle documentos em um único PDF.",icon:Combine},{id:"split",label:"Separar PDF",description:"Extraia intervalos ou cada página separadamente.",icon:Scissors},{id:"organize",label:"Organizar páginas",description:"Reordene, duplique, gire e exclua páginas.",icon:FileStack},{id:"converter",label:"Conversor",description:"Converta imagens em PDF ou PDF em imagens.",icon:FileImage},{id:"overtime",label:"Horas Extras PDF x Excel",description:"Cruze espelhos de ponto e insira horas automaticamente.",icon:FileInput},{id:"compare",label:"Comparar PDFs",description:"Compare estrutura, tamanho e texto extraído.",icon:FileDiff}];

export function PdfToolsPage(){const[tool,setTool]=useState<Tool>("home");return <>{tool==="home"?<><div className="page-heading"><div><h2>Central de ferramentas PDF</h2><p>Edite e processe documentos localmente no navegador, sem alterar os arquivos originais.</p></div><span className="privacy-pill">Processamento local · LGPD</span></div><div className="tool-card-grid pdf-grid">{tools.map(item=><button className="tool-card" key={item.id} onClick={()=>setTool(item.id)}><span><item.icon/></span><strong>{item.label}</strong><p>{item.description}</p><em>Abrir ferramenta →</em></button>)}</div></>:<><button className="back-link page-back" onClick={()=>setTool("home")}><ArrowLeft size={15}/> Central de PDFs</button>{tool==="editor"&&<PdfEditor/>}{tool==="merge"&&<MergeTool/>}{tool==="split"&&<SplitTool/>}{tool==="organize"&&<OrganizerTool/>}{tool==="converter"&&<ConverterTool/>}{tool==="overtime"&&<OvertimeTool/>}{tool==="compare"&&<CompareTool/>}</>}</>}

function ToolHeader({title,description}:{title:string;description:string}){return <div className="page-heading compact"><div><h2>{title}</h2><p>{description}</p></div></div>}

function MergeTool(){const{toast,addAudit}=useApp();const[files,setFiles]=useState<File[]>([]);const[busy,setBusy]=useState(false);const move=(index:number,direction:number)=>{const next=[...files];const target=index+direction;if(target<0||target>=files.length)return;[next[index],next[target]]=[next[target],next[index]];setFiles(next)};const run=async()=>{setBusy(true);try{await mergePdfs(files);addAudit({operation:"Juntou PDFs",module:"PDF",result:`${files.length} arquivos mesclados`,status:"SUCESSO",processedCount:files.length});toast("success","PDF unificado gerado","O arquivo PDF_UNIFICADO.pdf foi baixado.");}catch(error){toast("error","Não foi possível juntar os PDFs",error instanceof Error?error.message:undefined)}finally{setBusy(false)}};return <><ToolHeader title="Juntar PDFs" description="A ordem abaixo será preservada no PDF unificado."/><section className="surface import-surface"><div className="import-form"><FileDropzone accept=".pdf" multiple files={[]} onFiles={incoming=>setFiles(current=>[...current,...incoming])}/>{files.length>0&&<div className="sortable-files">{files.map((file,index)=><div key={`${file.name}-${index}`}><span>{index+1}</span><FileStack/><strong>{file.name}</strong><button disabled={index===0} onClick={()=>move(index,-1)} title="Mover para cima"><ArrowUp/></button><button disabled={index===files.length-1} onClick={()=>move(index,1)} title="Mover para baixo"><ArrowDown/></button><button onClick={()=>setFiles(files.filter((_,i)=>i!==index))} title="Remover"><Trash2/></button></div>)}</div>}<div className="form-actions"><button className="button primary" disabled={files.length<2||busy} onClick={run}><Combine size={16}/>{busy?"Juntando...":"Juntar e baixar"}</button></div></div></section></>}

function SplitTool(){const{toast,addAudit}=useApp();const[files,setFiles]=useState<File[]>([]);const[range,setRange]=useState("");const[individual,setIndividual]=useState(true);const[busy,setBusy]=useState(false);const run=async()=>{setBusy(true);try{await splitPdf(files[0],range.trim()||null,individual);addAudit({operation:"Separou PDF",module:"PDF",result:range||"Todas as páginas",status:"SUCESSO",fileName:files[0].name});toast("success","PDF separado com sucesso");}catch(error){toast("error","Não foi possível separar o PDF",error instanceof Error?error.message:undefined)}finally{setBusy(false)}};return <><ToolHeader title="Separar PDF" description="Informe páginas como 1-3, 5, 7-10 ou deixe em branco para todas."/><section className="surface import-surface"><div className="import-form"><FileDropzone accept=".pdf" files={files} onFiles={setFiles}/><div className="two-fields"><label className="field grow"><span>Intervalo de páginas</span><input placeholder="Ex.: 1-3, 5, 7-10" value={range} onChange={event=>setRange(event.target.value)}/></label><label className="field grow"><span>Formato da saída</span><select value={individual?"individual":"single"} onChange={event=>setIndividual(event.target.value==="individual")}><option value="individual">Um PDF por página (ZIP)</option><option value="single">Um PDF com o intervalo</option></select></label></div><button className="button primary align-start" disabled={!files.length||busy} onClick={run}><Scissors/>{busy?"Processando...":"Separar e baixar"}</button></div></section></>}

function OrganizerTool(){const{toast,addAudit}=useApp();const[files,setFiles]=useState<File[]>([]);const[count,setCount]=useState(0);const[pages,setPages]=useState<PageInstruction[]>([]);const[busy,setBusy]=useState(false);const onCount=useCallback((value:number)=>{setCount(value);setPages(Array.from({length:value},(_,sourceIndex)=>({sourceIndex,rotation:0})))},[]);const move=(index:number,dir:number)=>{const next=[...pages],target=index+dir;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setPages(next)};const run=async()=>{setBusy(true);try{await organizePdf(files[0],pages);addAudit({operation:"Organizou PDF",module:"PDF",result:`${pages.length} páginas geradas`,status:"SUCESSO",fileName:files[0].name});toast("success","PDF organizado e baixado");}catch(error){toast("error","Falha ao organizar PDF",error instanceof Error?error.message:undefined)}finally{setBusy(false)}};return <><ToolHeader title="Organizar páginas" description="Reordene, duplique, gire ou remova páginas antes de gerar o novo PDF."/><section className="surface import-surface"><div className="import-form"><FileDropzone accept=".pdf" files={files} onFiles={value=>{setFiles(value);setCount(0);setPages([])}}/>{files[0]&&<PdfPageCount file={files[0]} onCount={onCount}/>} {count>0&&<><div className="page-organizer">{pages.map((page,index)=><article key={`${page.sourceIndex}-${index}-${page.rotation}`}><div className="thumb-wrap"><PdfCanvas file={files[0]} pageNumber={page.sourceIndex+1} scale={.22}/><span>{index+1}</span></div><strong>Página original {page.sourceIndex+1}</strong><small>Rotação: {page.rotation}°</small><div><button disabled={index===0} onClick={()=>move(index,-1)} title="Mover para esquerda"><ArrowUp/></button><button disabled={index===pages.length-1} onClick={()=>move(index,1)} title="Mover para direita"><ArrowDown/></button><button onClick={()=>setPages(current=>current.map((item,i)=>i===index?{...item,rotation:(item.rotation+90)%360}:item))} title="Girar 90 graus"><RotateCw/></button><button onClick={()=>setPages(current=>[...current.slice(0,index+1),{...page},...current.slice(index+1)])} title="Duplicar"><Copy/></button><button onClick={()=>setPages(current=>current.filter((_,i)=>i!==index))} title="Excluir"><Trash2/></button></div></article>)}</div><div className="form-actions"><span>{pages.length} página(s) na saída</span><button className="button primary" disabled={!pages.length||busy} onClick={run}><Download/>{busy?"Gerando...":"Gerar novo PDF"}</button></div></>}</div></section></>}

function ConverterTool(){const{toast,addAudit}=useApp();const[mode,setMode]=useState<"images"|"pdf">("images");const[files,setFiles]=useState<File[]>([]);const[busy,setBusy]=useState(false);const run=async()=>{setBusy(true);try{if(mode==="images")await imagesToPdf(files);else await pdfToImages(files[0]);addAudit({operation:"Converteu arquivo",module:"PDF",result:mode==="images"?`${files.length} imagens para PDF`:"PDF para imagens",status:"SUCESSO",processedCount:files.length});toast("success","Conversão concluída");}catch(error){toast("error","Não foi possível converter",error instanceof Error?error.message:undefined)}finally{setBusy(false)}};return <><ToolHeader title="Conversor" description="Conversões reais executadas no navegador, sem apenas trocar a extensão."/><div className="mode-tabs"><button className={mode==="images"?"active":""} onClick={()=>{setMode("images");setFiles([])}}><ImageIcon/> JPG/PNG → PDF</button><button className={mode==="pdf"?"active":""} onClick={()=>{setMode("pdf");setFiles([])}}><FileImage/> PDF → imagens</button></div><section className="surface import-surface"><div className="import-form"><FileDropzone accept={mode==="images"?".jpg,.jpeg,.png":".pdf"} multiple={mode==="images"} files={files} onFiles={setFiles}/><button className="button primary align-start" disabled={!files.length||busy} onClick={run}><Download/>{busy?"Convertendo...":mode==="images"?"Gerar PDF":"Gerar imagens (ZIP)"}</button></div></section></>}

function CompareTool(){const{toast,addAudit}=useApp();const[original,setOriginal]=useState<File[]>([]);const[updated,setUpdated]=useState<File[]>([]);const[result,setResult]=useState<{a:{pageCount:number;pages:string[]};b:{pageCount:number;pages:string[]}}|null>(null);const[busy,setBusy]=useState(false);const run=async()=>{setBusy(true);try{const[a,b]=await Promise.all([extractPdfText(original[0]),extractPdfText(updated[0])]);setResult({a,b});addAudit({operation:"Comparou PDFs",module:"PDF",result:`${a.pageCount} x ${b.pageCount} páginas`,status:a.pages.join(" ")===b.pages.join(" ")?"SUCESSO":"AVISO"});}catch(error){toast("error","Falha ao comparar PDFs",error instanceof Error?error.message:undefined)}finally{setBusy(false)}};const diffs=useMemo(()=>result?Array.from({length:Math.max(result.a.pageCount,result.b.pageCount)},(_,index)=>({page:index+1,a:result.a.pages[index]??"",b:result.b.pages[index]??"",changed:(result.a.pages[index]??"")!==(result.b.pages[index]??"")})):[],[result]);return <><ToolHeader title="Comparar PDFs" description="Compare páginas, tamanho dos arquivos e o texto extraído."/><section className="surface import-surface"><div className="import-form"><div className="two-fields"><div className="grow"><label className="file-label">PDF ORIGINAL</label><FileDropzone accept=".pdf" files={original} onFiles={setOriginal}/></div><div className="grow"><label className="file-label">PDF NOVO</label><FileDropzone accept=".pdf" files={updated} onFiles={setUpdated}/></div></div><button className="button primary align-start" disabled={!original.length||!updated.length||busy} onClick={run}><FileDiff/>{busy?"Comparando...":"Comparar documentos"}</button></div></section>{result&&<div className="stack-gap top-gap"><div className="metrics-grid"><MetricCard label="PÁGINAS ORIGINAL" value={result.a.pageCount}/><MetricCard label="PÁGINAS NOVO" value={result.b.pageCount}/><MetricCard label="TAMANHO ORIGINAL" value={`${(original[0].size/1024).toFixed(1)} KB`}/><MetricCard label="TAMANHO NOVO" value={`${(updated[0].size/1024).toFixed(1)} KB`}/></div><section className="surface"><div className="section-header"><div><h3>Diferenças textuais por página</h3><p>{diffs.filter(item=>item.changed).length} página(s) com alterações</p></div></div><div className="pdf-diff-list">{diffs.map(diff=><div key={diff.page}><div><strong>Página {diff.page}</strong><StatusBadge status={diff.changed?(!diff.a?"ADICIONADA":!diff.b?"REMOVIDA":"DIVERGENTE"):"OK"}/></div><div className="side-by-side"><p>{diff.a||"Página ausente no original"}</p><p>{diff.b||"Página ausente no novo"}</p></div></div>)}</div></section></div>}</>}
