"use client";

import { useState } from "react";
import { CheckCircle2, Eye, EyeOff, FileSpreadsheet, LockKeyhole, ShieldCheck } from "lucide-react";
import { createSupabaseBrowserClient } from "../../src/lib/supabase/client";

export function LoginScreen(){
  const[show,setShow]=useState(false);const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  const login=async()=>{setBusy(true);setError("");try{const supabase=createSupabaseBrowserClient();const{error:e}=await supabase.auth.signInWithPassword({email,password});if(e){setError(e.message);return}window.location.href="/"}catch(e){setError(e instanceof Error?e.message:"Falha ao entrar") }finally{setBusy(false)}};
  return <main className="auth-page"><section className="auth-brand-panel"><div className="auth-brand"><img className="company-logo auth-company-logo" src="/logo-empresa-ui.png" alt="Logo da empresa"/><div><strong>RH Control</strong><small>Gestão administrativa</small></div></div><div className="auth-message"><span className="secure-label"><ShieldCheck/> Ambiente protegido</span><h1>Folha, benefícios e documentos em um só lugar.</h1><p>Uma central segura para conferências de RH, automação de planilhas e processamento de PDFs.</p><ul><li><CheckCircle2/> Processamento local de arquivos</li><li><CheckCircle2/> Permissões por perfil</li><li><CheckCircle2/> Histórico completo de auditoria</li></ul></div><small className="auth-lgpd">Privacidade e segurança em conformidade com a LGPD</small></section><section className="auth-form-panel"><div className="auth-form"><span className="auth-form-icon"><LockKeyhole/></span><h2>Acesse sua conta</h2><p>Entre com seu e-mail e senha do RH Control.</p><label className="field"><span>E-mail</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nome@empresa.com.br" autoComplete="email"/></label><label className="field"><span>Senha</span><div className="password-input"><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" autoComplete="current-password" onKeyDown={e=>{if(e.key==="Enter")void login()}}/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="inline-error">{error}</p>}<button className="button primary auth-submit" disabled={busy||!email||!password} onClick={()=>void login()}>{busy?"Entrando...":"Entrar com segurança"}</button><div className="auth-divider"><span>autenticação protegida pelo Supabase</span></div><p className="signup-link">Primeiro acesso? <a href="/cadastro">Criar conta</a></p><div className="auth-note"><FileSpreadsheet/><span>Novos usuários aguardam aprovação do administrador.</span></div></div></section></main>}

