import { bigint, boolean, date, doublePrecision, index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const profiles = pgTable("profiles", {
  id: uuid("id").primaryKey(), email: text("email").notNull(), fullName: text("full_name").notNull(),
  department: text("department").notNull().default(""), jobTitle: text("job_title").notNull().default(""),
  role: text("role", { enum: ["ADMINISTRADOR", "RH", "CONSULTA"] }).notNull().default("CONSULTA"),
  status: text("status", { enum: ["ATIVO", "AGUARDANDO APROVAÇÃO", "BLOQUEADO"] }).notNull().default("AGUARDANDO APROVAÇÃO"),
  createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull(),
}, table => [uniqueIndex("idx_profiles_email").on(table.email)]);
export const userPresence = pgTable("user_presence", { userId:uuid("user_id").primaryKey().references(()=>profiles.id), lastSeen:timestamp("last_seen",{withTimezone:true}).notNull() },table=>[index("idx_user_presence_last_seen").on(table.lastSeen)]);
export const systemSettings = pgTable("system_settings", { id:text("id").primaryKey().default("global"),maskCpf:boolean("mask_cpf").notNull().default(true),fileRetention:text("file_retention",{enum:["NONE","24_HOURS","SECURE_OPTIONAL"]}).notNull().default("NONE"),financialTolerance:numeric("financial_tolerance",{precision:12,scale:2}).notNull().default("0.01"),updatedBy:uuid("updated_by").references(()=>profiles.id),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow() });
export const rawFileUploads = pgTable("raw_file_uploads", { id:uuid("id").primaryKey().defaultRandom(),userId:uuid("user_id").notNull().references(()=>profiles.id),fileName:text("file_name").notNull(),storagePath:text("storage_path").notNull().unique(),sizeBytes:bigint("size_bytes",{mode:"number"}).notNull(),retentionMode:text("retention_mode",{enum:["24_HOURS","SECURE_OPTIONAL"]}).notNull(),expiresAt:timestamp("expires_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow() },table=>[index("idx_raw_file_uploads_user_created").on(table.userId,table.createdAt),index("idx_raw_file_uploads_expires").on(table.expiresAt)]);

export const employees = pgTable("employees", {
  id:uuid("id").primaryKey().defaultRandom(), fullName:text("full_name").notNull(), cpf:text("cpf").notNull().default(""), documentNumber:text("document_number").notNull().default(""),
  registration:text("registration").notNull().default(""), department:text("department").notNull().default(""), jobTitle:text("job_title").notNull().default(""),
  status:text("status",{enum:["ATIVO","DESLIGADO"]}).notNull().default("ATIVO"), source:text("source",{enum:["MANUAL","QUARK"]}).notNull().default("MANUAL"),
  externalId:text("external_id"), externalUnitId:text("external_unit_id"), externalUnitName:text("external_unit_name").notNull().default(""),
  externalTeamId:text("external_team_id"), externalTeamName:text("external_team_name").notNull().default(""), admissionDate:date("admission_date"), terminationDate:date("termination_date"),
  lastSyncedAt:timestamp("last_synced_at",{withTimezone:true}), createdBy:uuid("created_by").notNull().references(()=>profiles.id), updatedBy:uuid("updated_by").references(()=>profiles.id),
  createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(), updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow(),
},table=>[index("idx_employees_source").on(table.source),index("idx_employees_external_unit").on(table.externalUnitId)]);
export const employeeSyncRuns = pgTable("employee_sync_runs", {
  id:uuid("id").primaryKey().defaultRandom(), source:text("source").notNull().default("QUARK"), status:text("status").notNull(), triggeredBy:uuid("triggered_by").notNull().references(()=>profiles.id),
  triggeredByName:text("triggered_by_name").notNull(), unitsCount:integer("units_count").notNull().default(0), receivedCount:integer("received_count").notNull().default(0),
  createdCount:integer("created_count").notNull().default(0), updatedCount:integer("updated_count").notNull().default(0), linkedCount:integer("linked_count").notNull().default(0), skippedCount:integer("skipped_count").notNull().default(0),
  errorMessage:text("error_message"), startedAt:timestamp("started_at",{withTimezone:true}).notNull().defaultNow(), completedAt:timestamp("completed_at",{withTimezone:true}),
},table=>[index("idx_employee_sync_runs_started").on(table.startedAt)]);

export const roles = pgTable("roles", { id: uuid("id").primaryKey(), name: text("name").notNull().unique(), description: text("description").notNull() });
export const permissions = pgTable("permissions", { id: uuid("id").primaryKey(), key: text("key").notNull().unique(), description: text("description").notNull() });
export const rolePermissions = pgTable("role_permissions", { roleId:uuid("role_id").notNull().references(()=>roles.id), permissionId:uuid("permission_id").notNull().references(()=>permissions.id) });
export const payrollImports = pgTable("payroll_imports", { id:uuid("id").primaryKey().defaultRandom(),userId:uuid("user_id").notNull().references(()=>profiles.id),fileName:text("file_name").notNull(),fileSize:bigint("file_size",{mode:"number"}).notNull().default(0),competence:text("competence").notNull(),recordCount:integer("record_count").notNull(),status:text("status").notNull(),importedByName:text("imported_by_name").notNull().default(""),logs:jsonb("logs").notNull().default([]),isActive:boolean("is_active").notNull().default(false),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow() },table=>[uniqueIndex("uq_payroll_imports_competence").on(table.competence)]);
export const payrollRecords = pgTable("payroll_records", { id:uuid("id").primaryKey().defaultRandom(),payrollImportId:uuid("payroll_import_id").notNull().references(()=>payrollImports.id),cpf:text("cpf").notNull(),name:text("name").notNull(),liquid:doublePrecision("liquid").notNull().default(0),healthTotal:doublePrecision("health_total").notNull().default(0),dentalTotal:doublePrecision("dental_total").notNull().default(0),healthColumns:integer("health_columns").notNull().default(0),dentalColumns:integer("dental_columns").notNull().default(0),sourceSheet:text("source_sheet").notNull().default(""),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow() },table=>[index("idx_payroll_records_import").on(table.payrollImportId),index("idx_payroll_records_cpf").on(table.cpf)]);
export const processingJobs = pgTable("processing_jobs", { id:uuid("id").primaryKey(),userId:uuid("user_id").notNull().references(()=>profiles.id),type:text("type").notNull(),fileName:text("file_name"),status:text("status").notNull(),processedCount:integer("processed_count").default(0),okCount:integer("ok_count").default(0),divergentCount:integer("divergent_count").default(0),missingCount:integer("missing_count").default(0),createdAt:text("created_at").notNull(),completedAt:text("completed_at") },table=>[index("idx_processing_jobs_user_created").on(table.userId,table.createdAt),index("idx_processing_jobs_type_status").on(table.type,table.status)]);
export const comparisonResults = pgTable("comparison_results", { id:uuid("id").primaryKey(),jobId:uuid("job_id").notNull().references(()=>processingJobs.id),cpfHash:text("cpf_hash").notNull(),status:text("status").notNull(),payrollValue:doublePrecision("payroll_value"),referenceValue:doublePrecision("reference_value"),difference:doublePrecision("difference") });export const pdfJobs = pgTable("pdf_jobs", { id:uuid("id").primaryKey(),jobId:uuid("job_id").notNull().references(()=>processingJobs.id),tool:text("tool").notNull(),fileCount:integer("file_count").notNull(),createdAt:text("created_at").notNull() });
export const benefitJobs = pgTable("benefit_jobs", { id:uuid("id").primaryKey(),jobId:uuid("job_id").notNull().references(()=>processingJobs.id),benefitType:text("benefit_type").notNull(),configuration:text("configuration").notNull().default("{}") });
export const auditLogs = pgTable("audit_logs", { id:uuid("id").primaryKey(),userId:uuid("user_id").notNull().references(()=>profiles.id),userName:text("user_name").notNull(),operation:text("operation").notNull(),module:text("module").notNull(),result:text("result").notNull(),status:text("status").notNull(),fileName:text("file_name"),processedCount:integer("processed_count"),okCount:integer("ok_count"),divergentCount:integer("divergent_count"),missingCount:integer("missing_count"),createdAt:text("created_at").notNull() },table=>[index("idx_audit_logs_created").on(table.createdAt),index("idx_audit_logs_user_created").on(table.userId,table.createdAt)]);
