import { bigint, boolean, doublePrecision, index, integer, numeric, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const profiles = pgTable("profiles", {
  id: uuid("id").primaryKey(), email: text("email").notNull(), fullName: text("full_name").notNull(),
  department: text("department").notNull().default(""), jobTitle: text("job_title").notNull().default(""),
  role: text("role", { enum: ["ADMINISTRADOR", "RH", "CONSULTA"] }).notNull().default("CONSULTA"),
  status: text("status", { enum: ["ATIVO", "AGUARDANDO APROVAÇÃO", "BLOQUEADO"] }).notNull().default("AGUARDANDO APROVAÇÃO"),
  createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull(),
}, table => [uniqueIndex("idx_profiles_email").on(table.email)]);
export const userPresence = pgTable("user_presence", { userId:uuid("user_id").primaryKey().references(()=>profiles.id), lastSeen:timestamp("last_seen",{withTimezone:true}).notNull() },table=>[index("idx_user_presence_last_seen").on(table.lastSeen)]);
export const systemSettings = pgTable("system_settings", { id:text("id").primaryKey().default("global"),maskCpf:boolean("mask_cpf").notNull().default(true),fileRetention:text("file_retention",{enum:["NONE","24_HOURS","SECURE_OPTIONAL"]}).notNull().default("NONE"),financialTolerance:numeric("financial_tolerance",{precision:12,scale:2}).notNull().default("0.01"),updatedBy:uuid("updated_by").references(()=>profiles.id),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow() });
export const rawFileUploads = pgTable("raw_file_uploads", { id:uuid("id").primaryKey().defaultRandom(),userId:uuid("user_id").notNull().references(()=>profiles.id),fileName:text("file_name").notNull(),storagePath:text("storage_path").notNull().unique(),sizeBytes:bigint("size_bytes",{mode:"number"}).notNull(),retentionMode:text("retention_mode",{enum:["24_HOURS","SECURE_OPTIONAL"]}).notNull(),expiresAt:timestamp("expires_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow() },table=>[index("idx_raw_file_uploads_user_created").on(table.userId,table.createdAt),index("idx_raw_file_uploads_expires").on(table.expiresAt)]);

export const roles = pgTable("roles", { id: uuid("id").primaryKey(), name: text("name").notNull().unique(), description: text("description").notNull() });
export const permissions = pgTable("permissions", { id: uuid("id").primaryKey(), key: text("key").notNull().unique(), description: text("description").notNull() });
export const rolePermissions = pgTable("role_permissions", { roleId:uuid("role_id").notNull().references(()=>roles.id), permissionId:uuid("permission_id").notNull().references(()=>permissions.id) });
export const payrollImports = pgTable("payroll_imports", { id:uuid("id").primaryKey(),userId:uuid("user_id").notNull().references(()=>profiles.id),fileName:text("file_name").notNull(),competence:text("competence").notNull(),recordCount:integer("record_count").notNull(),status:text("status").notNull(),createdAt:text("created_at").notNull() });
export const processingJobs = pgTable("processing_jobs", { id:uuid("id").primaryKey(),userId:uuid("user_id").notNull().references(()=>profiles.id),type:text("type").notNull(),fileName:text("file_name"),status:text("status").notNull(),processedCount:integer("processed_count").default(0),okCount:integer("ok_count").default(0),divergentCount:integer("divergent_count").default(0),missingCount:integer("missing_count").default(0),createdAt:text("created_at").notNull(),completedAt:text("completed_at") },table=>[index("idx_processing_jobs_user_created").on(table.userId,table.createdAt),index("idx_processing_jobs_type_status").on(table.type,table.status)]);
export const comparisonResults = pgTable("comparison_results", { id:uuid("id").primaryKey(),jobId:uuid("job_id").notNull().references(()=>processingJobs.id),cpfHash:text("cpf_hash").notNull(),status:text("status").notNull(),payrollValue:doublePrecision("payroll_value"),referenceValue:doublePrecision("reference_value"),difference:doublePrecision("difference") });export const pdfJobs = pgTable("pdf_jobs", { id:uuid("id").primaryKey(),jobId:uuid("job_id").notNull().references(()=>processingJobs.id),tool:text("tool").notNull(),fileCount:integer("file_count").notNull(),createdAt:text("created_at").notNull() });
export const benefitJobs = pgTable("benefit_jobs", { id:uuid("id").primaryKey(),jobId:uuid("job_id").notNull().references(()=>processingJobs.id),benefitType:text("benefit_type").notNull(),configuration:text("configuration").notNull().default("{}") });
export const auditLogs = pgTable("audit_logs", { id:uuid("id").primaryKey(),userId:uuid("user_id").notNull().references(()=>profiles.id),userName:text("user_name").notNull(),operation:text("operation").notNull(),module:text("module").notNull(),result:text("result").notNull(),status:text("status").notNull(),fileName:text("file_name"),processedCount:integer("processed_count"),okCount:integer("ok_count"),divergentCount:integer("divergent_count"),missingCount:integer("missing_count"),createdAt:text("created_at").notNull() },table=>[index("idx_audit_logs_created").on(table.createdAt),index("idx_audit_logs_user_created").on(table.userId,table.createdAt)]);
