import { eq } from "drizzle-orm";
import { getChatGPTUser } from "../../chatgpt-auth";
import { getDb } from "../../../db";
import { profiles } from "../../../db/schema";
import { getOrCreateProfile } from "../../../src/server/profile";

async function requireAdmin(){const user=await getChatGPTUser();if(!user)return null;const profile=await getOrCreateProfile(user);return profile.role==="ADMINISTRADOR"&&profile.status==="ATIVO"?profile:null}
export async function GET(){if(!await requireAdmin())return Response.json({error:"Acesso negado"},{status:403});const rows=await getDb().select().from(profiles);return Response.json({users:rows.map(row=>({id:row.id,name:row.fullName,email:row.email,department:row.department,jobTitle:row.jobTitle,role:row.role,status:row.status}))})}
export async function POST(request:Request){if(!await requireAdmin())return Response.json({error:"Acesso negado"},{status:403});const payload=await request.json() as {name?:string;email?:string;department?:string;jobTitle?:string;role?:"ADMINISTRADOR"|"RH"|"CONSULTA"};if(!payload.name?.trim()||!payload.email?.trim())return Response.json({error:"Nome e e-mail são obrigatórios"},{status:400});const now=new Date().toISOString();const value={id:`invite:${crypto.randomUUID()}`,fullName:payload.name.trim(),email:payload.email.trim().toLowerCase(),department:payload.department?.trim()??"",jobTitle:payload.jobTitle?.trim()??"",role:payload.role??"CONSULTA",status:"AGUARDANDO APROVAÇÃO" as const,createdAt:now,updatedAt:now};try{await getDb().insert(profiles).values(value);return Response.json({user:{id:value.id,name:value.fullName,email:value.email,department:value.department,jobTitle:value.jobTitle,role:value.role,status:value.status}},{status:201})}catch{return Response.json({error:"Já existe um usuário com este e-mail."},{status:409})}}
export async function PATCH(request:Request){const admin=await requireAdmin();if(!admin)return Response.json({error:"Acesso negado"},{status:403});const payload=await request.json() as {id?:string;role?:"ADMINISTRADOR"|"RH"|"CONSULTA";status?:"ATIVO"|"AGUARDANDO APROVAÇÃO"|"BLOQUEADO"};if(!payload.id||payload.id===admin.id)return Response.json({error:"Não é permitido alterar o próprio acesso por esta tela."},{status:400});await getDb().update(profiles).set({...(payload.role?{role:payload.role}:{}),...(payload.status?{status:payload.status}:{}),updatedAt:new Date().toISOString()}).where(eq(profiles.id,payload.id));return Response.json({ok:true})}
