import { createSupabaseServerClient } from "../../../src/lib/supabase/server";
import { createSupabaseAdminClient } from "../../../src/lib/supabase/admin";
import { getCurrentProfile } from "../../../src/server/auth";

const roles=["ADMINISTRADOR","RH","CONSULTA"] as const;const statuses=["ATIVO","AGUARDANDO APROVAÇÃO","BLOQUEADO"] as const;type Role=typeof roles[number];type Status=typeof statuses[number];
const serialize=(row:any)=>({id:row.id,name:row.full_name,email:row.email,department:row.department,jobTitle:row.job_title,role:row.role,status:row.status});
async function requireAdmin(){const profile=await getCurrentProfile();return profile?.role==="ADMINISTRADOR"&&profile.status==="ATIVO"?profile:null}

export async function GET(){if(!await requireAdmin())return Response.json({error:"Acesso negado"},{status:403});const supabase=await createSupabaseServerClient();const{data,error}=await supabase.from("profiles").select("id,email,full_name,department,job_title,role,status").order("full_name");if(error)return Response.json({error:error.message},{status:500});return Response.json({users:(data??[]).map(serialize)})}

export async function POST(request:Request){if(!await requireAdmin())return Response.json({error:"Acesso negado"},{status:403});const payload=await request.json() as {name?:string;email?:string;department?:string;jobTitle?:string;role?:Role};if(!payload.name?.trim()||!payload.email?.trim())return Response.json({error:"Nome e e-mail são obrigatórios"},{status:400});if(payload.role&&!roles.includes(payload.role))return Response.json({error:"Perfil inválido"},{status:400});const admin=createSupabaseAdminClient();const redirectTo=`${process.env.NEXT_PUBLIC_APP_URL??new URL(request.url).origin}/auth/callback?next=/cadastro`;const{data,error}=await admin.auth.admin.inviteUserByEmail(payload.email.trim().toLowerCase(),{redirectTo,data:{full_name:payload.name.trim(),department:payload.department?.trim()??"",job_title:payload.jobTitle?.trim()??""}});if(error||!data.user)return Response.json({error:error?.message??"Falha ao criar convite"},{status:400});await admin.from("profiles").update({full_name:payload.name.trim(),department:payload.department?.trim()??"",job_title:payload.jobTitle?.trim()??"",role:payload.role??"CONSULTA",status:"AGUARDANDO APROVAÇÃO",updated_at:new Date().toISOString()}).eq("id",data.user.id);const{data:row}=await admin.from("profiles").select("id,email,full_name,department,job_title,role,status").eq("id",data.user.id).single();return Response.json({user:row?serialize(row):null},{status:201})}

export async function PATCH(request:Request){if(!await requireAdmin())return Response.json({error:"Acesso negado"},{status:403});const payload=await request.json() as {id?:string;role?:Role;status?:Status};if(!payload.id||(!payload.role&&!payload.status))return Response.json({error:"Informe o usuário e a alteração desejada."},{status:400});if(payload.role&&!roles.includes(payload.role))return Response.json({error:"Perfil inválido"},{status:400});if(payload.status&&!statuses.includes(payload.status))return Response.json({error:"Status inválido"},{status:400});const supabase=await createSupabaseServerClient();const{data,error}=await supabase.rpc("admin_update_profile",{target_id:payload.id,new_role:payload.role??null,new_status:payload.status??null});if(error)return Response.json({error:error.message},{status:400});return Response.json({ok:true,user:serialize(data)})}
